version: '3.8'

services:

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: where-is-everyone-bot
    restart: always
    container_name: where-is-everyone-bot

    # user: 1000:1000
    user: "${MY_UID}:${GID}"

    ports:
      - "${API_PORT}:8050"
    depends_on:
      - db
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - mynetwork
 
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./db/data:/var/lib/postgresql/data

    #
    user: "${MY_UID}:${GID}"

    networks:
      mynetwork:
        aliases:
          - database

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    #
    user: "${MY_UID}:${GID}"

    networks:
      - mynetwork
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    networks:
      - mynetwork
    volumes:
      - ./db/migrations:/migrations

    # user: 1000:1000
    user: "${MY_UID}:${GID}"

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
    command: [
      "-path",
      "/migrations",
      "-database",
      "postgres://\
      $POSTGRES_USER:\
      $POSTGRES_PASSWORD@\
      $POSTGRES_HOST:\
      $POSTGRES_PORT/\
      $POSTGRES_DB?\
      sslmode=disable",
      "up"]
    links: 
      - db

networks:
  mynetwork: